### ISSUE TITLE
Sign up completely broken

### ISSUE THREAD

**Issue by itsmeurbi** [bryanmg/ammdk_colima#14]
Currently it's impossible to sign in due to model validations and missing user inputs in sign up form

<img width="1891" alt="Screen Shot 2022-01-25 at 19 14 36" src="https://user-images.githubusercontent.com/26292224/151086793-3522e7fa-a6ca-4324-96ad-5cb826a62a5e.png">

**Comment by bryanmg** [comment]
Fixed on https://github.com/bryanmg/ammdk_colima/pull/19
