### ISSUE TITLE
Broken user seeds

### ISSUE THREAD

**Issue by itsmeurbi** [bryanmg/ammdk_colima#15]
User seeds are not being created the right way, making impossible to used them to access system. Looks like password it's not being encrypted.

<img width="1891" alt="Screen Shot 2022-01-25 at 19 15 59" src="https://user-images.githubusercontent.com/26292224/151086996-0fc91159-3ab2-4b71-a796-d4de5d44ef1f.png">
<img width="1467" alt="Screen Shot 2022-01-25 at 19 16 03" src="https://user-images.githubusercontent.com/26292224/151087010-c2888252-dbf4-4fba-a3f8-337bc60f5055.png">

**Comment by bryanmg** [comment]
Fixed on https://github.com/bryanmg/ammdk_colima/pull/19
