### ISSUE TITLE
Broken group routes

### ISSUE THREAD

**Issue by itsmeurbi** [bryanmg/ammdk_colima#17]
Groups routes is not using the right format:

<img width="1891" alt="Screen Shot 2022-01-25 at 19 23 32" src="https://user-images.githubusercontent.com/26292224/151087389-a4740ba6-184c-4fdd-8c37-29ad66223d86.png">

**Comment by bryanmg** [comment]
Fixed on https://github.com/bryanmg/ammdk_colima/pull/19
