### ISSUE TITLE
Impossible to log out

### ISSUE THREAD

**Issue by itsmeurbi** [bryanmg/ammdk_colima#18]
I can't even log ou
<img width="1891" alt="Screen Shot 2022-01-25 at 19 34 02" src="https://user-images.githubusercontent.com/26292224/151088344-7c727bad-90f5-47fb-bf8a-15c38314a083.png">

**Comment by bryanmg** [comment]
Fixed on https://github.com/bryanmg/ammdk_colima/pull/19
